[package]
name = "bencode"
version = "0.1.0"
authors = ["Travis Kaufman <travis.kaufman@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"

[dependencies]
serde = "*"
itoa = "*"
